# Generated by Django 2.2.28 on 2025-05-06 21:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campusonline", "0078_linz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("size", models.PositiveIntegerField(editable=False, null=True)),
                ("digest", models.CharField(editable=False, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="campusonline.Organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on", models.DateTimeField(auto_now_add=True)),
                ("total", models.PositiveIntegerField()),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.Model",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.Token"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstalledModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("running", models.BooleanField(default=False, editable=False)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "info",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        editable=False, null=True
                    ),
                ),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.Backend"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.Model"
                    ),
                ),
            ],
            options={
                "unique_together": {("backend", "model")},
            },
        ),
    ]
