# Generated by Django 4.2.28 on 2026-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backend",
            options={"ordering": ("url",)},
        ),
        migrations.AlterModelOptions(
            name="installedmodel",
            options={"ordering": ("model__name", "backend__url")},
        ),
        migrations.AlterModelOptions(
            name="model",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="token",
            options={"ordering": ("organization__name",)},
        ),
        migrations.AlterField(
            model_name="installedmodel",
            name="info",
            field=models.JSONField(editable=False, null=True),
        ),
    ]
